Экзамен
ArtemCoolAc/2019-2-Atom-Frontend-A-Kutuzov pull request #10
Opened 2019-12-17 18:02 UTC by ArtemCoolAc

# Экзамен

Прошу @martinkomitsky, @chexex или @priver проверить его.

Что было сделано:
1. Создан проект
2. Сверстано
*
*

2019-12-17 18:11 UTC, chexex commented
https://github.com/track-mail-ru/tt-fullstack/blob/master/atom-2019-2020/front/exam/exam.md
до пересдачи

2019-12-19 05:14 UTC, martinkomitsky requested changes
Ждем выполнения задания до конца

2019-12-24 02:40 UTC, ArtemCoolAc commented
Не смог до конца доделать, времени не осталось. Что-то получилось, более-менее. Надеюсь, нормально. На пересдачу приехать не смогу, к сожалению.

2019-12-26 07:02 UTC, chexex approved these changes
4 балла

Для ревью недостаточно кода :(

2019-12-26 07:02 UTC, chexex commented on exam/my-app/src/Components/App.js
> +    routes_list.push(<Route path={path}><DetailedWeather city={city}/></Route>)
Зачем два списка вести?

2019-12-26 07:02 UTC, chexex commented on exam/my-app/src/Components/DetailedForecast.js
> +  const { isLoading, data } = useFetch(`${API_URL}${API_KEY}`);
неплохо

2019-12-26 07:02 UTC, chexex commented on exam/my-app/src/Components/DetailedForecast.js
> +  ];
DRY
```js
for (const i in Array.from({length: 6})) {
  hours.push(<DetailedTwo {...data} num={i+1} />
}
```

2019-12-26 07:03 UTC, closed without merging